# Standard imports
from typing import Annotated, Any, List

# Third party imports
from pydantic import BaseModel, Field


class ContextResponse(BaseModel):
    """
    Pydantic model that represents the standard response structure for the Agents.
    """
    answer: Annotated[str, "Answer generated by the system."] = Field(default="", description="Answer generated by the system.")
    context: Annotated[List[Any], "Context used to generate the answer"] = Field(default=[], description="Context used to generate the answer")


class SuccesfulResponse(BaseModel):
    """
    Pydantic model that represent the standard succesful response structure.
    """
    succesful: Annotated[bool, "Succesful response flag"] = Field(default="", description="Succesful response flag")


class ErrorResponse(BaseModel):
    """
    Pydantic model that represent the standard succesful response structure.
    """
    detail: Annotated[str, "Error message"] = Field(default="", description="Error message")
    status_code: Annotated[int, "status code"] = Field(default="", description="status code")
    reason: Annotated[int, "error reason"] = Field(default="", description="error reason")
